name: Build and Publish

on:
  release:
    types: [created]

jobs:
  Build_Deploy:
    runs-on: product.lambda
    steps:
      - uses: actions/checkout@v2
      - name: Clone AWS Infra
        uses: actions/checkout@v2
        with:
          repository: DhrubaBaishya/aws_infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: resources/aws/infra
          ref: develop
      - name: Get Config
        run: |
          cp resources/aws/infra/product.lambda.aws/* .
          ls
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots package
#      - uses: hashicorp/setup-terraform@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
#      - name: Deploy Resources with CloudFormation
#        id: amplify-stack
#        uses: aws-actions/aws-cloudformation-github-deploy@v1
#        with:
#          name: test
#          template: stack.yml
#      - name: Terraform init
#        id: init
#        run: terraform init
#      - name: Terraform plan
#        id: plan
#        run: terraform plan
#      - name: Terraform apply
#        id: apply
#        run: terraform apply -auto-approve -input=false