name: Build and Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  Build_Publish:
    runs-on: product.lambda
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
#      - uses: hashicorp/setup-terraform@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots package
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      maven_version: ${{ steps.project.outputs.version }}
#      - name: Deploy Resources with CloudFormation
#        id: amplify-stack
#        uses: aws-actions/aws-cloudformation-github-deploy@v1
#        with:
#          name: test
#          template: stack.yml
  Deploy:
    runs-on: product.lambda
    needs: Build_Publish
    environment: 'dev'
    env:
      version: ${{ needs.Build_Publish.outputs.maven_version }}
    steps:
      - name: Download package
        run: |
          curl 'https://maven.pkg.github.com/DhrubaBaishya/product.lambda/store.product.lambda/${{ needs.Build_Publish.outputs.maven_version }}/product.lambda-${{ needs.Build_Publish.outputs.maven_version }}.jar' \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -L \
          -O
      - name: List Files
        run: |
          ls
      - name: Clone AWS Infra
        uses: actions/checkout@v2
        with:
          repository: DhrubaBaishya/aws_infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: resources/aws/infra
          ref: develop
      - name: Get Config
        run: |
          cp resources/aws/infra/product.lambda.aws/* .
          ls
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan -var="maven_project_version=${{ needs.Build_Publish.outputs.maven_version }}"
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false -var="maven_project_version=${{ needs.Build_Publish.outputs.maven_version }}"